-- setup plugins
require("setup.colors")
require("setup.lsp")
require("setup.null_ls")
require("setup.lspkind")
require("setup.cmp")
require("setup.lsp_signature")
require("setup.goto_preview")
require("setup.telescope")
require("setup.git")
require("setup.fidget")
require("setup.todo")
require("setup.toggleterm")
require("setup.treesitter")
require("setup.evilline")
